apiVersion: v1
kind: Pod
metadata:
    name: postgres-pod 
    labels:
        name: postgres-pod
        app: demo-voting-pod 
        
spec:
      containers:
       - name: postgres 
         image: postgres:9.4 
         args: ["-e", "POSTGRES_HOST_AUTH_METHOD=trust"]
                       
         ports:
           - containerPort: 5432
