apiVersion: v1
kind: Pod
metadata:
    name: redis-pod 
    labels:
        name: redist-pod
        app: demo-voting-pod 
        
spec:
      containers:
       - name: redis 
         image: redis 
         ports:
           - containerPort: 6379
